# Generated by Django 5.2.7 on 2025-11-02 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_duration_course_duration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_date',
        ),
        migrations.AddField(
            model_name='course',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percent', 'percent'), ('amount', 'amount')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='product.chapter'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='product.course'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='product.chapter'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
