# Generated by Django 5.2.7 on 2025-11-24 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_course_teachers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['title', '-number']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['title', '-number']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title', '-final_price', 'type', 'activate']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['title', '-number']},
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='product.category'),
        ),
    ]
